create database ShopQuanAo
go
use ShopQuanAo
go

USE [ShopQuanAo]
GO

/****** Object:  Table [dbo].[KhachHang]    Script Date: 9/13/2024 9:09:30 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KhachHang](
	[ID_KH] [int] NOT NULL,
	[HoTen_KH] [nvarchar](100) NOT NULL,
	[SDT_KH] [nvarchar](15) NOT NULL,
	[Dia_Chi] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_KhachHang] PRIMARY KEY CLUSTERED 
(
	[ID_KH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ShopQuanAo]
GO

/****** Object:  Table [dbo].[DanhMuc]    Script Date: 9/13/2024 9:19:07 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DanhMuc](
	[ID_DM] [int] NOT NULL,
	[Ten_DM] [nvarchar](50) NOT NULL,
	[MieuTa_DM] [nvarchar](250) NOT NULL,
 CONSTRAINT [PK_DanhMuc] PRIMARY KEY CLUSTERED 
(
	[ID_DM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ShopQuanAo]
GO

/****** Object:  Table [dbo].[SanPham]    Script Date: 9/13/2024 9:50:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SanPham](
	[ID_SP] [int] NOT NULL,
	[Ten_SP] [nvarchar](50) NOT NULL,
	[MieuTa_SP] [nvarchar](250) NOT NULL,
	[Gia_SP] [int] NOT NULL,
	[TonKho] [int] NOT NULL,
	[ID_DM] [int] NOT NULL,
 CONSTRAINT [PK_SanPham] PRIMARY KEY CLUSTERED 
(
	[ID_SP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ShopQuanAo]
GO

/****** Object:  Table [dbo].[DonHang]    Script Date: 9/13/2024 9:51:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DonHang](
	[ID_DH] [int] NOT NULL,
	[ID_KH] [int] NOT NULL,
	[Date] [datetime] NOT NULL,
	[SoLuong] [int] NOT NULL,
 CONSTRAINT [PK_DonHang] PRIMARY KEY CLUSTERED 
(
	[ID_DH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ShopQuanAo]
GO

/****** Object:  Table [dbo].[NhanVien]    Script Date: 9/13/2024 9:53:26 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NhanVien](
	[ID_NV] [int] NOT NULL,
	[HoTen_NV] [nvarchar](100) NOT NULL,
	[SDT_NV] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_NhanVien] PRIMARY KEY CLUSTERED 
(
	[ID_NV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [ShopQuanAo]
GO

/****** Object:  Table [dbo].[NhaCungCap]    Script Date: 9/13/2024 9:53:55 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NhaCungCap](
	[ID_NCC] [int] NOT NULL,
	[Ten_NCC] [nvarchar](100) NOT NULL,
	[SDT_NCC] [nvarchar](15) NOT NULL,
	[DiaChi_NCC] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_NhaCungCap2] PRIMARY KEY CLUSTERED 
(
	[ID_NCC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


